export enum N2WidgetType {
	PAGE = 'Page',

	INPUT = 'Input',
	NUMBER = 'Number',
	PASSWORD = 'Pwd',
	DECORATE_INPUT = 'DecoInput',
	DECORATE_NUMBER = 'DecoNumber',
	DECORATE_PASSWORD = 'DecoPwd',
	TEXTAREA = 'Textarea',
	CHECKBOX = 'Checkbox',
	CHECKBOXES = 'Checkboxes',
	CHECKS = 'Checks',
	RADIO = 'Radio',
	RADIOS = 'Radios',
	BUTTON = 'Button',
	LINK = 'Link',
	BUTTON_BAR = 'ButtonBar',
	CAPTION = 'Caption',
	LABEL = 'Label',
	BADGE = 'Badge',
	DROPDOWN = 'Dropdown',
	MULTI_DROPDOWN = 'MultiDropdown',
	CALENDAR = 'Calendar',
	DATE = 'Date',
	DATETIME = 'DateTime',
	TIME = 'Time',

	RIBS = 'Ribs',
	READONLY_RIBS = 'RibsView',

	TABLE_ROW_OPERATORS = 'RowOperators',
	TABLE = 'Table',

	SECTION = 'Section',
	BOX = 'Box',
	TAB = 'Tab',
	TABS = 'Tabs',
	WIZARD_SHARED = 'WShared',
	WIZARD_STEP = 'WStep',
	WIZARD = 'Wizard',
	TREE = 'Tree',
	DROPDOWN_TREE = 'DropdownTree',
	DDT = 'DDT',
	MULTI_DROPDOWN_TREE = 'MultiDropdownTree',
	MDDT = 'MDDT',

	PAGINATION = 'Pagination'
}
