export enum ParsedNodeType {
	HEADING,
	LIST, LIST_ITEM,
	PARAGRAPH, CODE, TEXT, EMPHASIS, STRONG, DELETE, INLINE_CODE,
	TABLE, TABLE_ROW, TABLE_CELL,
	LINK, LINK_REFERENCE,
	IMAGE, IMAGE_REFERENCE,
	FOOTNOTE, FOOTNOTE_DEFINITION, FOOTNOTE_REFERENCE,
	BREAK, THEMATIC_BREAK, BLOCKQUOTE, HTML, DEFINITION,
	YAML
}