import {redressByCutPrefix} from '../../standard-widgets';

export const enUSIntlLabels = redressByCutPrefix({
	'claim.title': 'Claim',
	'claim.menu.label': 'Claim',
	'claim.registration.menu.label': 'Registration',
	'claim.registration.title': 'Registration',
	'claim.registration.find-insured.title': 'Claim - Registration - Find Insured',
	'claim.registration.create.title': 'Claim - Registration - Create',
	'claim.registration.case-no': 'Registration of Case No.:',
	'claim.registration.criteria.keywords.placeholder': 'Enter to trigger search, could be registration No., policy No. or insured name.',
	'claim.registration.results.related-policies': 'Related Policies',
	'claim.registration.results.ongoing-claims': 'Ongoing Claims',
	'claim.registration.action.register': 'Register',
	'claim.acceptance.menu.label': 'Acceptance',
	'claim.acceptance.title': 'Acceptance',
	'claim.acceptance.find.title': 'Claim - Acceptance - Find',
	'claim.acceptance.claim-entry.title': 'Claim - Acceptance - Claim Entry',
	'claim.acceptance.claim-entry.case-no': 'Claim Entry of Case No.:',
	'claim.acceptance.policy-acceptance.title': 'Claim - Acceptance - Policy Acceptance',
	'claim.acceptance.policy-acceptance.case-no': 'Policy Acceptance of Case No.:',
	'claim.evaluation.menu.label': 'Evaluation',
	'claim.evaluation.title': 'Evaluation',
	'claim.evaluation.case-no': 'Evaluation of Case No.:',
	'claim.reg.case-no': 'Case No.',
	'claim.reg.reg-no': 'Registration No.',
	'claim.reg.submission-channel': 'Submission Channel',
	'claim.reg.manual-register': 'Manual Registration',
	'claim.reg.status': 'Case Status',
	'claim.insured.title': 'Insured Information',
	'claim.claim.title': 'Claim Information',
	'claim.claim.type': 'Claim Type',
	'claim.claim.notification-date': 'Notification Date',
	'claim.claim.event-date': 'Event Date',
	'claim.claim.nature': 'Claim Nature',
	'claim.claim.incident-code': 'Incident Code',
	'claim.claim.case-classification': 'Case Classification',
	'claim.claim.previous-case-no': 'Previous Case No.',
	'claim.claim.diagnosis-code': 'Diagnosis Code',
	'claim.claim.details': 'Event Details',
	'claim.claim.type-required': 'Claim type is required.',
	'claim.claim.notification-date-required': 'Notification date is required.',
	'claim.claim.event-date-required': 'Event date is required.',
	'claim.claim.nature-required': 'Claim nature is required.',
	'claim.additional.title': 'Additional Information',
	'claim.additional.hospital-code': 'Hospital Code',
	'claim.additional.admission-date': 'Admission Date',
	'claim.additional.discharge-date': 'Discharge Date',
	'claim.additional.treat-place': 'Place of Treatment',
	'claim.additional.foreign-hospital': 'Foreign Hospital',
	'claim.additional.doctor-code': 'Doctor Code',
	'claim.additional.unknown-pre-existing-conditions': 'Unknown Pre-existing Conditions',
	'claim.additional.chronic-disease': 'Chronic Disease',
	'claim.additional.actual-ward-level': 'Actual Ward Level',
	'claim.additional.voluntary-ward-upgrade': 'Voluntary Ward Upgrade',
	'claim.additional.direct-billing-indicator': 'Direct Billing Indicator',
	'claim.reporter.title': 'Reporter Information',
	'claim.reporter.relationship': 'Relationship with Insured',
	'claim.reporter.via': 'Report Via',
	'claim.reporter.name': 'Reporter Name',
	'claim.reporter.type-of-pass': 'Type of Pass',
	'claim.reporter.notification-method': 'Notification Method',
	'claim.reporter.handling-producer': 'Handling Producer',
	'claim.reporter.producer-mobile': 'Producer Mobile No.',
	'claim.reporter.producer-email': 'Producer Email',
	'claim.actions-and-supporting': 'Actions & Supporting:',
	'claim.claim-issue.title': 'Claim Issue',
	'claim.claim-issue.headline': 'Title',
	'claim.claim-issue.raised': 'Generated',
	'claim.claim-issue.last-updated': 'Last Updated',
	'claim.claim-issue.status': 'Status',
	'claim.claim-issue.description': 'Description',
	'claim.claim-issue.add-title': 'Add a Manual Issue',
	'claim.query-letter.title': 'Query Letter',
	'claim.query-letter.doc-no': 'Doc. No.',
	'claim.query-letter.doc-name': 'Doc. Name',
	'claim.query-letter.due': 'Due Date',
	'claim.query-letter.raised': 'Generated',
	'claim.query-letter.last-updated': 'Last Updated',
	'claim.query-letter.status': 'Status',
	'claim.internal-query.title': 'Internal Query',
	'claim.internal-query.query-no': 'Query No.',
	'claim.internal-query.query-type': 'Type',
	'claim.internal-query.query-title': 'Title',
	'claim.internal-query.assignee': 'Assignee',
	'claim.internal-query.due': 'Due Date',
	'claim.internal-query.raised': 'Generated',
	'claim.internal-query.last-updated': 'Last Updated',
	'claim.internal-query.status': 'Status',
	'claim.escalation.title': 'Escalation',
	'claim.escalation.to': 'Escalated To',
	'claim.escalation.due': 'Due Date',
	'claim.escalation.raised': 'Escalated',
	'claim.escalation.last-updated': 'Last Updated',
	'claim.escalation.status': 'Status',
	'claim.escalation.headline': 'Title',
	'claim.escalation.description': 'Description',
	'claim.escalation.add-title': 'Raise an Escalation',
	'claim.investigation.title': 'Investigation',
	'claim.investigation.to': 'Submitted To',
	'claim.investigation.due': 'Due Date',
	'claim.investigation.raised': 'Submitted',
	'claim.investigation.last-updated': 'Last Updated',
	'claim.investigation.status': 'Status',
	'claim.investigation.headline': 'Title',
	'claim.investigation.description': 'Description',
	'claim.investigation.add-title': 'Request an Investigation',
	'claim.underwriting-by-claim.title': 'Underwriting',
	'claim.underwriting-by-claim.type': 'Underwriting Type',
	'claim.underwriting-by-claim.case-no': 'Case No.',
	'claim.underwriting-by-claim.application-date': 'Application Date',
	'claim.underwriting-by-claim.raised': 'Submitted',
	'claim.underwriting-by-claim.due': 'Due Date',
	'claim.underwriting-by-claim.replied': 'Replied',
	'claim.underwriting-by-claim.status': 'Status',
	'claim.acceptance-decision.title': 'Acceptance Decision',
	'claim.acceptance-decision.policy-title': 'Policy Information of Policy No.',
	'claim.acceptance-decision.policy-holder': 'Policy Holder',
	'claim.acceptance-decision.current-status': 'Current Policy Status',
	'claim.acceptance-decision.status-at-event': 'Policy Status at Event Date',
	'claim.acceptance-decision.currency': 'Policy Currency',
	'claim.acceptance-decision.bankruptcy-involved': 'Bankruptcy Involved',
	'claim.acceptance-decision.service-agent': 'Service Agent',
	'claim.acceptance-decision.service-agent-mobile': 'Service Agent Mobile',
	'claim.acceptance-decision.product.name': 'Product Name',
	'claim.acceptance-decision.product.acceptable': 'Acceptable',
	'claim.acceptance-decision.product.accept': 'Accept',
	'claim.acceptance-decision.product.notified-amount': 'Notified Amount',
	'claim.acceptance-decision.product.sum-assured': 'Sum Assured',
	'claim.acceptance-decision.product.status-at-event': 'Product Status at Event Date',
	'claim.acceptance-decision.product.current-status': 'Current Product Status',
	'claim.acceptance-decision.product.commencement-date': 'Commencement Date',
	'claim.acceptance-decision.product.expiry-date': 'Expiry Date',
	'claim.acceptance-decision.product.reinsurance': 'Reinsurance',
	'claim.acceptance-decision.summary-title': 'Decision',
	'claim.acceptance-decision.decision': 'Decision',
	'claim.acceptance-decision.reason': 'Reason',
	'claim.acceptance-decision.price-eff-date': 'Price Effective Date(ILP)',
	'claim.acceptance-decision.comment-to-client': 'Comments to Client',
	'claim.claim-workbench.title': 'Claim Workbench',
	'claim.claim-workbench.life-assured-info.title': 'Life Assured Info',
	'claim.claim-workbench.life-assured-info.age-at-event': 'Age at Event Date',
	'claim.claim-workbench.life-assured-info.medical-or-not.title': 'Medical/Non-Medical Code Information',
	'claim.claim-workbench.life-assured-info.medical-or-not.code': 'Code',
	'claim.claim-workbench.life-assured-info.medical-or-not.code-category': 'Code Category',
	'claim.claim-workbench.life-assured-info.medical-or-not.lia-code-type': 'LIA Code Type',
	'claim.claim-workbench.life-assured-info.medical-or-not.description': 'Medical/Non-Medical Code Description',
	'claim.claim-workbench.life-assured-info.claim-history.title': 'Claim History',
	'claim.claim-workbench.life-assured-info.claim-history.product-code': 'Product Code',
	'claim.claim-workbench.life-assured-info.claim-history.product-type': 'Product Type',
	'claim.claim-workbench.life-assured-info.claim-history.claim-type': 'Claim Type',
	'claim.claim-workbench.life-assured-info.claim-history.event-date': 'Event Date',
	'claim.claim-workbench.life-assured-info.claim-history.claim-nature': 'Claim Nature',
	'claim.claim-workbench.life-assured-info.claim-history.diagnosis': 'Diagnostic Code',
	'claim.claim-workbench.life-assured-info.claim-history.claim-status': 'Claim Status',
	'claim.claim-workbench.life-assured-info.claim-history.claim-decision': 'Claim Decision',
	'claim.claim-workbench.life-assured-info.claim-history.claimable-amount': 'Claimable Amount',
	'claim.claim-workbench.life-assured-info.claim-history.settle-date': 'Settle Date',
	'claim.claim-workbench.life-assured-info.underwriting-history.title': 'Underwriting History',
	'claim.claim-workbench.life-assured-info.underwriting-history.product-code': 'Product Code',
	'claim.claim-workbench.life-assured-info.underwriting-history.product-type': 'Product Type',
	'claim.claim-workbench.life-assured-info.underwriting-history.business-type': 'Business Type',
	'claim.claim-workbench.life-assured-info.underwriting-history.underwriting-decision': 'UW Decision',
	'claim.claim-workbench.life-assured-info.underwriting-history.commencement-date': 'Commencement Date',
	'claim.claim-workbench.life-assured-info.underwriting-history.policy-status': 'Policy Status',
	'claim.claim-workbench.life-assured-info.underwriting-history.premium-status': 'Premium Status',
	'claim.claim-workbench.life-assured-info.underwriting-history.payment-frequency': 'Payment Frequency',
	'claim.claim-workbench.life-assured-info.underwriting-history.sa-unit-level': 'SA / Unit / Level',
	'claim.claim-workbench.life-assured-info.underwriting-history.annual-premium': 'Annual Premium',
	'claim.claim-workbench.life-assured-info.underwriting-history.auto-underwriting-indicator': 'Auto UW Indicator',
	'claim.claim-workbench.policies.title': 'Policy Basic Information',
	'claim.claim-workbench.policy.title': 'Policy Information of Policy No.:',
	'claim.claim-workbench.policy.proposal-date': 'Proposal Date',
	'claim.claim-workbench.policy.issue-date': 'Issue Date',
	'claim.claim-workbench.policy.risk-commencement-date': 'Risk Commencement Date',
	'claim.claim-workbench.policy.currency': 'Currency',
	'claim.claim-workbench.policy.status': 'Policy Status',
	'claim.claim-workbench.policy.lapse-date': 'Lapse Date',
	'claim.claim-workbench.policy.reinstatement-date': 'Reinstatement Date',
	'claim.claim-workbench.policy.installment-premium': 'Installment Premium',
	'claim.claim-workbench.policy.next-due-date': 'Next Due Date',
	'claim.claim-workbench.policy.outstanding-premium': 'Outstanding Premium',
	'claim.claim-workbench.policy.policy-frequency': 'Policy Frequency',
	'claim.claim-workbench.policy.policy-loan': 'Policy Loan',
	'claim.claim-workbench.policy.sales-channel': 'Sales Channel',
	'claim.claim-workbench.policy.service-agent': 'Service Agent',
	'claim.claim-workbench.policy.party.title': 'Parties',
	'claim.claim-workbench.policy.party.role': 'Party Role',
	'claim.claim-workbench.policy.party.name': 'Customer Name',
	'claim.claim-workbench.policy.party.id-type-and-no': 'ID Type / No.',
	'claim.claim-workbench.policy.party.relation-with-holder': 'Relation with PH',
	'claim.claim-workbench.policy.party.annual-income': 'Annual Income',
	'claim.claim-workbench.policy.party.smoker-status': 'Smoker Status',
	'claim.claim-workbench.policy.party.risk-indicator': 'Risk Indicator',
	'claim.claim-workbench.policy.party.medical-report': 'Medical Report',
	'claim.claim-workbench.policy.party.declaration': 'Declaration',
	'claim.claim-workbench.policy.product.title': 'Products',
	'claim.claim-workbench.policy.product.name': 'Product Name',
	'claim.claim-workbench.policy.product.life-assured': 'Life Assured',
	'claim.claim-workbench.policy.product.risk-commencement-date': 'Risk Commencement Date',
	'claim.claim-workbench.policy.product.status': 'Policy Status',
	'claim.claim-workbench.policy.product.reinstatement-date': 'Reinstatement Date',
	'claim.claim-workbench.policy.product.coverage-period': 'Coverage Period',
	'claim.claim-workbench.policy.product.payment-period': 'Payment Period',
	'claim.claim-workbench.policy.product.sa-unit-level': 'SA / Unit / Level',
	'claim.claim-workbench.policy.product.installment-premium': 'Installment Premium',
	'claim.claim-workbench.policy.product.underwriting-decision': 'Underwriting Decision',
	'claim.claim-workbench.policy.product.loading': 'Loading',
	'claim.claim-workbench.policy.product.agreement': 'Agreement',
	'claim.claim-workbench.policy.product.lapse-terminate-date': 'Lapse / Terminate Date',
	'claim.claim-workbench.policy.product.inception-to-event-duration': 'Duration from Inception to Event',
	'claim.claim-workbench.policy.product.reinstatement-to-event-duration': 'Duration from Reinstatement to Event',
	'claim.claim-workbench.policy.loading.title': 'Loading',
	'claim.claim-workbench.policy.loading.product-code': 'Product Code',
	'claim.claim-workbench.policy.loading.product-type': 'Product Type',
	'claim.claim-workbench.policy.loading.category': 'Loading Category',
	'claim.claim-workbench.policy.loading.occupation-class': 'Occupation Class',
	'claim.claim-workbench.policy.loading.type': 'Loading Type',
	'claim.claim-workbench.policy.loading.period': 'Loading Period',
	'claim.claim-workbench.policy.loading.extra-premium': 'Extra Premium',
	'claim.claim-workbench.policy.exclusion.title': 'Exclusion',
	'claim.claim-workbench.policy.exclusion.product-code': 'Product Code',
	'claim.claim-workbench.policy.exclusion.product-type': 'Product Type',
	'claim.claim-workbench.policy.exclusion.category': 'Loading Category',
	'claim.claim-workbench.policy.exclusion.occupation-class': 'Occupation Class',
	'claim.claim-workbench.policy.exclusion.type': 'Loading Type',
	'claim.claim-workbench.policy.exclusion.period': 'Loading Period',
	'claim.claim-workbench.policy.exclusion.extra-premium': 'Extra Premium',
	'claim.claim-workbench.policy.agreement.title': 'Agreement',
	'claim.claim-workbench.policy.agreement.product-code': 'Product Code',
	'claim.claim-workbench.policy.agreement.product-type': 'Product Type',
	'claim.claim-workbench.policy.agreement.type': 'Agreement Type',
	'claim.claim-workbench.policy.agreement.life-assured': 'Life Assured',
	'claim.claim-workbench.policy.agreement.code': 'Agreement Code',
	'claim.claim-workbench.policy.agreement.comment': 'Agreement Comment',
	'claim.claim-workbench.policy.agreement.review-period': 'Review Period (Month)',
	'claim.claim-workbench.policy.agreement.content': 'Content',
	'claim.claim-workbench.policy.risk-related-cs-history.title': 'Risk Related CS History',
	'claim.claim-workbench.policy.risk-related-cs-history.product-code': 'Product Code',
	'claim.claim-workbench.policy.risk-related-cs-history.product-type': 'Product Type',
	'claim.claim-workbench.policy.risk-related-cs-history.item': 'CS Item',
	'claim.claim-workbench.policy.risk-related-cs-history.application-date': 'CS Application Date',
	'claim.claim-workbench.policy.risk-related-cs-history.status': 'CS Status',
	'claim.claim-workbench.policy.risk-related-cs-history.auto-underwriting-indicator': 'Auto UW Indicator',
	'claim.claim-workbench.policy.risk-related-cs-history.underwriting-decision': 'UW Decision',
	'claim.claim-workbench.policy.risk-related-cs-history.underwriting-completion-date': 'UW Completion Date',
	'claim.claim-workbench.policy.risk-related-cs-history.underwriter': 'Underwriter',
	'claim.claim-workbench.assessment.title': 'Assessment Information',
	'claim.claim-workbench.assessment.policy.title': 'Policy No.:',
	'claim.claim-workbench.assessment.policy.product.name': 'Product Name',
	'claim.claim-workbench.assessment.policy.product.claim-decision': 'Claim Decision',
	'claim.claim-workbench.assessment.policy.product.claim-decision-reason': 'Decision Reason',
	'claim.claim-workbench.assessment.policy.product.in-force': 'In Force',
	'claim.claim-workbench.assessment.policy.product.premium-waive': 'Premium Waive',
	'claim.claim-workbench.assessment.policy.product.waive-start-date': 'Waive Start Date',
	'claim.claim-workbench.assessment.policy.product.total-payment-amount': 'Total Product Payment Amount',
	'claim.claim-workbench.assessment.policy.product.item-name': 'Liability / Adjustment Items',
	'claim.claim-workbench.assessment.policy.product.item-payment': 'Claimable / Incurred Payment',
	'claim.claim-workbench.assessment.policy.product.item-actual-payment': 'Actual Payment',
	'claim.claim-workbench.assessment.policy.product.adjustment-item-name': 'Policy Adjustment Item',
	'claim.claim-workbench.assessment.policy.product.adjustment-item-evaluation-payment': 'Evaluation Payment',
	'claim.claim-workbench.assessment.policy.product.adjustment-item-actual-payment': 'Actual Payment',
	'claim.claim-workbench.assessment.total-disbursement-amount': 'Total Policy Disbursement Amount:',
	'claim.claim-workbench.disbursement-plan.title': 'Disbursement Plan',
	'claim.claim-workbench.disbursement-plan.policy.title': 'Policy No.:',
	'claim.claim-workbench.disbursement-plan.payment.payee': 'Payee',
	'claim.claim-workbench.disbursement-plan.payment.relationship': 'Relationship',
	'claim.claim-workbench.disbursement-plan.payment.payment-method': 'Payment Method',
	'claim.claim-workbench.disbursement-plan.payment.product-code': 'Product',
	'claim.claim-workbench.disbursement-plan.payment.payment-type': 'Type',
	'claim.claim-workbench.disbursement-plan.payment.percentage': 'Percentage',
	'claim.claim-workbench.disbursement-plan.payment.disbursement-amount': 'Disbursement Amount',
	'claim.claim-workbench.disbursement-plan.payment.interest-amount': 'Interest',
	'claim.claim-workbench.disbursement-plan.payment.payment-amount-on-payment-currency': 'Payment Amount (Pay Currency)',
	'claim.claim-workbench.disbursement-plan.payment.payment-amount-on-policy-currency': 'Payment Amount (Policy Currency)',
	'claim.claim-workbench.disbursement-plan.payment.pending': 'Pending',
	'claim.claim-workbench.disbursement-plan.total-disbursement-amount': 'Total Policy Disbursement Amount:',
	'claim.claim-workbench.disbursement-plan.total-adjustment-amount': 'Adjustment Amount:',
	'claim.claim-workbench.internal-external-query.title': 'Internal and External Query',
	'claim.claim-workbench.internal-external-query.task': 'Task',
	'claim.claim-workbench.internal-external-query.query-type': 'Query Type',
	'claim.claim-workbench.internal-external-query.sub-type': 'Sub Type',
	'claim.claim-workbench.internal-external-query.status': 'Status',
	'claim.claim-workbench.internal-external-query.generated': 'Generated',
	'claim.claim-workbench.internal-external-query.submission-content': 'Submission Content',
	'claim.claim-workbench.internal-external-query.replied': 'Replied',
	'claim.claim-workbench.internal-external-query.reply-comment': 'Reply Comments',
	'claim.claim-workbench.comment-history.title': 'Comment History',
	'claim.assessment.title': 'Assessment',
	'claim.assessment.policy.title': 'Policy No.:',
	'claim.assessment.policy.current-status': 'Current Policy Status',
	'claim.assessment.policy.inception-date': 'Inception Date',
	'claim.assessment.policy.last-reinstatement-date': 'Last Reinstatement Date',
	'claim.assessment.policy.premium-frequency': 'Premium Frequency',
	'claim.assessment.policy.anniversary-date': 'Anniversary Date',
	'claim.assessment.policy.status-at-event': 'Policy Status at Event Date',
	'claim.assessment.payment-summary.title': 'Policy Payment Summary',
	'claim.assessment.product.name': 'Product',
	'claim.assessment.product.life-assured': 'Life Assured',
	'claim.assessment.product.claim-decision': 'Claim Decision',
	'claim.assessment.product.claim-decision-reason': 'Reason',
	'claim.assessment.product.in-force': 'Inforce',
	'claim.assessment.product.premium-waive': 'Premium Waive',
	'claim.assessment.product.waive-start-date': 'Waive Date',
	'claim.assessment.product.total-payment-amount': 'Total Product Payment Amount',
	'claim.assessment.payment-summary.total-disbursement-amount': 'Total Policy Disbursement Amount',
	'claim.assessment.adjustment-item.name': 'Adjustment Item',
	'claim.assessment.adjustment-item.premium-collect-to': 'Premium Collect To',
	'claim.assessment.adjustment-item.evaluation-payment': 'Evaluation Amount',
	'claim.assessment.adjustment-item.actual-payment': 'Payment Amount',
	'claim.assessment.adjustment-item.remark': 'Remark',
	'claim.disbursement-plan.title': 'Disbursement Plan',
	'claim.disbursement-plan.summary.title': 'Disbursement Plan Summary',
	'claim.disbursement-plan.summary.total-disbursement-amount': 'Total Disbursement Amount:',
	'claim.disbursement-plan.policy.total-disbursement-amount': 'Total Disbursement Amount',
	'claim.disbursement-plan.policy.allocated-disbursement-amount': 'Allocated Disbursement Amount',
	'claim.disbursement-plan.policy.total-adjusted-payment': 'Total Adjusted Payment',
	'claim.disbursement-plan.policy.currency': 'Policy Currency',
	'claim.disbursement-plan.policy.product.name': 'Product',
	'claim.disbursement-plan.policy.product.disbursement-amount': 'Product Disbursement Amount',
	'claim.disbursement-plan.benefit-amount-allocation.title': 'Benefit Amount Allocation',
	'claim.disbursement-plan.benefit-amount-allocation.payee': 'Payee',
	'claim.disbursement-plan.benefit-amount-allocation.disbursement-method': 'Disbursement Method',
	'claim.disbursement-plan.benefit-amount-allocation.product-code': 'Product',
	'claim.disbursement-plan.benefit-amount-allocation.payment-type': 'Type',
	'claim.disbursement-plan.benefit-amount-allocation.percentage': 'Percentage',
	'claim.disbursement-plan.benefit-amount-allocation.disbursement-amount': 'Disbursement Amount',
	'claim.disbursement-plan.benefit-amount-allocation.interest-amount': 'Interest',
	'claim.disbursement-plan.benefit-amount-allocation.payment-amount-on-payment-currency': 'Payment Amount (Pay Currency)',
	'claim.disbursement-plan.benefit-amount-allocation.payment-amount-on-policy-currency': 'Payment Amount (Policy Currency)',
	'claim.disbursement-plan.benefit-amount-allocation.pending': 'Pending',
	'claim.disbursement-plan.add-lump-sum': 'Add Lump Sum',
	'claim.disbursement-plan.add-installment': 'Add Installment',
	// biz properties
	'claim.props.policy-no': 'Policy No.',
	'claim.props.cs-no': 'CS No.',
	'claim.props.claim-no': 'Claim No.',
	'claim.props.insured-name': 'Insured Name',
	'claim.props.id-type': 'ID Type',
	'claim.props.id-no': 'ID Number',
	'claim.props.gender': 'Gender',
	'claim.props.dob': 'DOB',
	'claim.props.nationality': 'Nationality',
	'claim.props.occupation': 'Occupation',
	'claim.props.postcode': 'Postcode',
	'claim.props.mobile': 'Mobile No.',
	'claim.props.email': 'Email',
	'claim.props.address1': 'Address line 1',
	'claim.props.address2': 'Address line 2',
	'claim.props.address3': 'Address line 3',
	'claim.props.address4': 'Address line 4',
	// actions
	'claim.action.image': 'Image',
	'claim.action.doc-checklist': 'Document Checklist',
	'claim.action.medical-bill': 'Medical Bill',
	'claim.action.history': 'History',
	'claim.action.edit-case': 'Edit Case Info',
	'claim.action.accept-policy': 'Accept Policy',
	'claim.action.change-insured': 'Change Insured',
	'claim.action.search-reporter': 'Search Reporter',
	'claim.action.generate-issues-as-internal-query': 'Generate Internal Query',
	'claim.action.generate-issues-as-query-letter': 'Generate Query Letter',
	'claim.action.add-claim-issue': 'Add a Manual Issue',
	'claim.action.add-escalation': 'Raise an Escalation',
	'claim.action.add-investigation': 'Request an Investigation',
	'claim.action.reply': 'Reply',
	'claim.action.reminder': 'Reminder',
	'claim.action.withdraw': 'Withdraw',
	'claim.action.comment': 'Comment',
	'claim.action.reload-policy': 'Reload Policy'
}, 'claim');
