export const CALENDAR_DATE_FORMAT = 'YYYY/MM/DD';
export const CALENDAR_TIME_FORMAT = 'HH:mm:ss';
export const CALENDAR_DATETIME_FORMAT = `${CALENDAR_DATE_FORMAT} ${CALENDAR_TIME_FORMAT}`;

export const DEFAULTS = {
	DATE_FORMAT: CALENDAR_DATE_FORMAT,
	TIME_FORMAT: CALENDAR_TIME_FORMAT,
	DATETIME_FORMAT: CALENDAR_DATETIME_FORMAT,
	AUTO_CONFIRM: true,
	USE_CALENDAR_ICON: false
};
