name: Align version

on:
  workflow_call:
    inputs:
      ref:
        description: The branch or tag name.
        required: true
        type: string
      branch:
        description: Pre-release branch
        required: true
        type: string
      version:
        description: Target version
        required: true
        type: string

jobs:
  align-version:
    name: Align module versions
    runs-on: ubuntu-latest
    steps:
      - name: Echo inputs
        run: |
          echo "Ref: [${{ inputs.ref }}]"
          echo "Pre-release branch: [${{ inputs.branch }}]"
          echo "Target version: [${{ inputs.version }}]"
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}
      - name: Change Version of d9-ts-vfs
        uses: ./.github/actions/change-node-version/
        id: change-node-version-d9-ts-vfs
        with:
          module-name: d9-ts-vfs
          target-version: ${{ inputs.version }}
      - name: Change Version of d9-n1
        uses: ./.github/actions/change-node-version/
        id: change-node-version-d9-n1
        with:
          module-name: d9-n1
          target-version: ${{ inputs.version }}
      - name: Change Version of d9-n2
        uses: ./.github/actions/change-node-version/
        id: change-node-version-d9-n2
        with:
          module-name: d9-n2
          target-version: ${{ inputs.version }}
      - name: Change Version of d9-n3
        uses: ./.github/actions/change-node-version/
        id: change-node-version-d9-n3
        with:
          module-name: d9-n3
          target-version: ${{ inputs.version }}
      - name: Change Version of d9-n5
        uses: ./.github/actions/change-node-version/
        id: change-node-version-d9-n5
        with:
          module-name: d9-n5
          target-version: ${{ inputs.version }}
      - name: Change Version of d9-n6
        uses: ./.github/actions/change-node-version/
        id: change-node-version-d9-n6
        with:
          module-name: d9-n6
          target-version: ${{ inputs.version }}
      - name: Change Version of d9-code-editor
        uses: ./.github/actions/change-node-version/
        id: change-node-version-d9-code-editor
        with:
          module-name: d9-code-editor
          target-version: ${{ inputs.version }}
      - name: Change Version of d9-echarts
        uses: ./.github/actions/change-node-version/
        id: change-node-version-d9-echarts
        with:
          module-name: d9-echarts
          target-version: ${{ inputs.version }}
      - name: Change Version of d9-sample-cra
        uses: ./.github/actions/change-node-version/
        id: change-node-version-d9-sample-cra
        with:
          module-name: d9-sample-cra
          target-version: ${{ inputs.version }}
      - name: Change Version of d9-thai-plan-selection
        uses: ./.github/actions/change-node-version/
        id: change-node-version-d9-thai-plan-selection
        with:
          module-name: d9-thai-plan-selection
          target-version: ${{ inputs.version }}
      - name: Change Version of d9-n99
        uses: ./.github/actions/change-node-version/
        id: change-node-version-d9-n99
        with:
          module-name: d9-n99
          target-version: ${{ inputs.version }}
      - name: Change Version of create-rainbow-d9-app
        uses: ./.github/actions/change-node-version/
        id: change-node-version-create-rainbow-d9-app
        with:
          module-name: create-rainbow-d9-app
          target-version: ${{ inputs.version }}
      - name: Create pre release branch
        run: git checkout -b ${{ inputs.branch }}
      - name: Initialize mandatory git config
        run: |
          git config user.name "brad.wu"
          git config user.email brad.wu@ebaotech.com
      - name: Commit config and manifest files
        id: make-commit
        run: |
          git add .
          git commit --message "Module version aligned to [${{ inputs.version }}]"
          git tag pre-release-${{ inputs.version }}
      - name: Push new branch
        run: git push --force origin ${{ inputs.branch }} --tags